version: '3.9'
services:
  db:
    container_name: db-app
    image: postgres:alpine
    hostname: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - connection

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - EXPOSE_PORT=${APP_PORT}
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - APP_ORIGIN=${APP_ORIGIN}
      - APP_SECRET=${APP_SECRET}
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - connection
    depends_on:
      - db

networks:
  connection:
    driver: bridge
