// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
	"tags": [
        {
            "name": "user",
            "description": "Route path about user API"
        },
        {
            "name": "product",
            "description": "Route path about product API"
        },
        {
            "name": "order",
            "description": "Route path about order API"
        },
        {
            "name": "admin",
            "description": "Route path about admin API"
        }
    ],
    "paths": {
        "/api/v1/user/register": {
            "post": {
                "tags": [
                    "user"
                ],
                "summary": "Register new user",
                "description": "Create new user",
                "operationId": "registerUser",
                "requestBody": {
                    "description": "Register new user",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UserRegister"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "201": {
                        "description": "Account Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponseUserRegister"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/user/login": {
            "post": {
                "tags": [
                    "user"
                ],
                "summary": "Login user into the system",
                "description": "Login user",
                "operationId": "loginUser",
                "requestBody": {
                    "description": "Login user into the system",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UserLogin"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Success Login",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponseUserLogin"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/product/create": {
            "post": {
                "tags": [
                    "admin",
                    "owner"
                ],
                "summary": "Create New Product",
                "description": "Create Product",
                "operationId": "productCreate",
                "requestBody": {
                    "description": "Create new Product",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Product"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "201": {
                        "description": "Product Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponseProduct"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "sorry you are not admin or owner",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "authorization": []
                    }
                ]
            }
        },
        "/api/v1/product/category/{id}": {
            "get": {
                "tags": [
                    "product"
                ],
                "summary": "Get all product by category ID",
                "description": "Get all product by category ID",
                "operationId": "getByCategory",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID of category product",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Product Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponsePaginationProduct"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "authorization": []
                    }
                ]
            }
        },
        "/api/v1/product/find/{id}": {
            "get": {
                "tags": [
                    "product"
                ],
                "summary": "Get product by ID",
                "description": "Get product by ID",
                "operationId": "getByProductID",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID of product",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Product Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponseProduct"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "authorization": []
                    }
                ]
            }
        },
        "/api/v1/product/find": {
            "get": {
                "tags": [
                    "product"
                ],
                "summary": "Get All Product",
                "description": "Get All Product",
                "operationId": "getAllProduct",
                "parameters": [
                    {
                        "name": "page",
                        "in": "query",
                        "description": "Page query for get page",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "per_page",
                        "in": "query",
                        "description": "Total data to show in one page",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Product Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponsePaginationProduct"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "authorization": []
                    }
                ]
            }
        },
        "/api/v1/product/get": {
            "get": {
                "tags": [
                    "product"
                ],
                "summary": "Get All Product By Search",
                "description": "Get All Product By Search",
                "operationId": "getAllProductBySearch",
                "parameters": [
                    {
                        "name": "page",
                        "in": "query",
                        "description": "Page query for get page",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "per_page",
                        "in": "query",
                        "description": "Total data to show in one page",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "search",
                        "in": "query",
                        "description": "You can use name product to search product",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Product Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponsePaginationProduct"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "authorization": []
                    }
                ]
            }
        },
        "/api/v1/category/create": {
            "post": {
                "tags": [
                    "admin"
                ],
                "summary": "Create New Category",
                "description": "Create Category",
                "operationId": "categoryCreate",
                "requestBody": {
                    "description": "Create new Category",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Category"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "201": {
                        "description": "Category Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponseCreateCategory"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "sorry you are not admin or owner",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "authorization": []
                    }
                ]
            }
        },
        "/api/v1/order/buy": {
            "post": {
                "tags": [
                    "order"
                ],
                "summary": "Create New Order",
                "description": "Create New Order",
                "operationId": "createOrder",
                "requestBody": {
                    "description": "Create new Order",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Order"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "201": {
                        "description": "Order Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponseBuy"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "authorization": []
                    }
                ]
            }
        },
        "/api/v1/order/add": {
            "post": {
                "tags": [
                    "order"
                ],
                "summary": "Adding product to cart",
                "description": "Adding product to  cart",
                "operationId": "addToCart",
                "requestBody": {
                    "description": "add product to cart",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Cart"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "201": {
                        "description": "Success add to cart",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponseCart"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "authorization": []
                    }
                ]
            }
        },
        "/api/v1/order/cart": {
            "post": {
                "tags": [
                    "order"
                ],
                "summary": "List cart",
                "description": "List cart",
                "operationId": "listCart",
                "responses": {
                    "200": {
                        "description": "List cart found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponseListCart"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "authorization": []
                    }
                ]
            }
        },
        "/api/v1/order/checkout/{id}": {
            "post": {
                "tags": [
                    "order"
                ],
                "summary": "Checkout product by cart id",
                "description": "Checkout product by cart id",
                "operationId": "checkoutProduct",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID of Cart",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success checkout product",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponseBuy"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "authorization": []
                    }
                ]
            }
        },
        "/api/v1/order/pay/{uuid}": {
            "put": {
                "tags": [
                    "order"
                ],
                "summary": "Pay product at order by UUID",
                "description": "Pay order by UUID",
                "operationId": "payOrder",
                "parameters": [
                    {
                        "name": "uuid",
                        "in": "path",
                        "description": "UUID of Order",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Pay Order",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponsePay"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "authorization": []
                    }
                ]
            }
        },
        "/api/v1/order/history": {
            "get": {
                "tags": [
                    "order"
                ],
                "summary": "Get All history Order",
                "description": "Get All history Order",
                "operationId": "historyOrder",
                "responses": {
                    "200": {
                        "description": "Product Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponseHistoryOrder"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "authorization": []
                    }
                ]
            }
        },
        "/api/v1/order/find/{uuid}": {
            "get": {
                "tags": [
                    "order"
                ],
                "summary": "Get order by UUID",
                "description": "Get order by UUID",
                "operationId": "getOrderByUUID",
                "parameters": [
                    {
                        "name": "uuid",
                        "in": "path",
                        "description": "UUID of Order",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Product Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponseOrder"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ApiResponse"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "authorization": []
                    }
                ]
            }
        }
    },
    "components": {
        "schemas": {
            "UserRegister": {
                "required": [
                    "name",
                    "email",
                    "password",
                    "nohp"
                ],
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "example": "John Doe"
                    },
                    "email": {
                        "type": "string",
                        "example": "johndoe@co.id"
                    },
                    "password": {
                        "type": "string",
                        "example": "th1s_1s_c335t"
                    },
                    "nohp": {
                        "type": "integer",
                        "format": "int64",
                        "example": 85467432323
                    }
                }
            },
            "UserLogin": {
                "required": [
                    "email",
                    "password"
                ],
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string",
                        "example": "johndoe@co.id"
                    },
                    "password": {
                        "type": "string",
                        "example": "th1s_1s_c335t"
                    }
                }
            },
            "ResponseUserRegister": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "example": "John Doe"
                    },
                    "email": {
                        "type": "string",
                        "example": "johndoe@co.id"
                    }
                }
            },
            "ResponseUserLogin": {
                "type": "object",
                "properties": {
                    "token": {
                        "type": "string",
                        "example": "thi1s_3s_tok5n_j45"
                    }
                }
            },
            "ApiResponseUserRegister": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "message": {
                        "type": "string"
                    },
                    "data": {
                        "$ref": "#/components/schemas/ResponseUserRegister"
                    }
                }
            },
            "ApiResponseUserLogin": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "message": {
                        "type": "string"
                    },
                    "data": {
                        "$ref": "#/components/schemas/ResponseUserLogin"
                    }
                }
            },
            "Product": {
                "required": [
                    "name",
                    "price",
                    "owner",
                    "discount",
                    "description",
                    "expire_at",
                    "stock",
                    "category_id"
                ],
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "name of product",
                        "example": "Laptop"
                    },
                    "price": {
                        "type": "integer",
                        "format": "int64",
                        "example": 10000
                    },
                    "owner": {
                        "type": "string",
                        "description": "owner of product",
                        "example": "John Doe"
                    },
                    "discount": {
                        "type": "integer",
                        "format": "float64",
                        "example": 0.1
                    },
                    "description": {
                        "type": "string",
                        "description": "description of product",
                        "example": "John Doe"
                    },
                    "expire_at": {
                        "type": "string",
                        "description": "time expire product"
                    },
                    "stock": {
                        "type": "integer",
                        "format": "int64",
                        "example": 100
                    },
                    "category_id": {
                        "type": "integer",
                        "format": "int64",
                        "example": 1
                    }
                }
            },
            "ProductResponse": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int64",
                        "example": 1
                    },
                    "name": {
                        "type": "string",
                        "description": "name of product",
                        "example": "Laptop"
                    },
                    "price": {
                        "type": "integer",
                        "format": "int64",
                        "example": 10000
                    },
                    "owner": {
                        "type": "string",
                        "description": "owner of product",
                        "example": "John Doe"
                    },
                    "discount": {
                        "type": "integer",
                        "format": "float64",
                        "example": 0.1
                    },
                    "description": {
                        "type": "string",
                        "description": "description of product",
                        "example": "John Doe"
                    },
                    "expire_at": {
                        "type": "string",
                        "description": "time expire product"
                    },
                    "stock": {
                        "type": "integer",
                        "format": "int64",
                        "example": 100
                    },
                    "category_id": {
                        "type": "integer",
                        "format": "int64",
                        "example": 1
                    }
                }
            },
            "ApiResponseProduct": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "message": {
                        "type": "string"
                    },
                    "data": {
                        "$ref": "#/components/schemas/ProductResponse"
                    }
                }
            },
            "ApiResponsePaginationProduct": {
                "type": "object",
                "properties": {
                    "_metadata": {
                        "$ref": "#/components/schemas/Metadata"
                    },
                    "data": {
                        "$ref": "#/components/schemas/GetProductResponse"
                    }
                }
            },
            "GetProductResponse": {
                "type": "array",
                "items": {
                    "$ref": "#/components/schemas/ProductResponse"
                }
            },
            "Category": {
                "required": [
                    "name",
                    "description"
                ],
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "name of category",
                        "example": "Electronic"
                    },
                    "description": {
                        "type": "string",
                        "description": "description of category",
                        "example": "This is category electronic"
                    }
                }
            },
            "ApiResponseCreateCategory": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "message": {
                        "type": "string"
                    },
                    "data": {
                        "$ref": "#/components/schemas/Category"
                    }
                }
            },
            "Order": {
                "required": [
                    "userId",
                    "productId",
                    "total"
                ],
                "type": "object",
                "properties": {
                    "userId": {
                        "type": "integer",
                        "format": "int64",
                        "example": 1
                    },
                    "productId": {
                        "type": "integer",
                        "format": "int64",
                        "example": 1
                    },
                    "total": {
                        "type": "integer",
                        "format": "int64",
                        "example": 10
                    },
                    "status": {
                        "type": "string",
                        "description": "Order Status",
                        "example": "processed",
                        "enum": [
                            "processed",
                            "paid"
                        ]
                    }
                }
            },
            "OrderResponse": {
                "type": "object",
                "properties": {
                    "uuid": {
                        "type": "integer",
                        "format": "int64",
                        "example": 1
                    },
                    "username": {
                        "type": "string",
                        "example": "John Doe"
                    },
                    "name": {
                        "type": "string",
                        "description": "name of product",
                        "example": "Laptop"
                    },
                    "price": {
                        "type": "integer",
                        "format": "int64",
                        "example": 10000
                    },
                    "owner": {
                        "type": "string",
                        "description": "owner of product",
                        "example": "John Doe"
                    },
                    "discount": {
                        "type": "integer",
                        "format": "float64",
                        "example": 0.1
                    },
                    "description": {
                        "type": "string",
                        "description": "description of product"
                    },
                    "expire_at": {
                        "type": "string",
                        "description": "time expire product"
                    },
                    "status": {
                        "type": "string",
                        "description": "Order Status",
                        "example": "processed",
                        "enum": [
                            "processed",
                            "paid"
                        ]
                    }
                }
            },
            "PaymentResponse": {
                "type": "object",
                "properties": {
                    "uuid": {
                        "type": "string",
                        "example": "ORDER-VsdPjgd-1845763"
                    },
                    "product_name": {
                        "type": "string",
                        "description": "name of product",
                        "example": "Laptop"
                    },
                    "product_price": {
                        "type": "integer",
                        "format": "int64",
                        "example": 10000
                    },
                    "product_owner": {
                        "type": "string",
                        "description": "owner of product",
                        "example": "John Doe"
                    },
                    "product_discount": {
                        "type": "integer",
                        "format": "float64",
                        "example": 0.1
                    },
                    "product_description": {
                        "type": "string",
                        "description": "description of product"
                    },
                    "product_expire": {
                        "type": "string",
                        "description": "time expire product"
                    },
                    "total_harga": {
                        "type": "integer",
                        "format": "int64",
                        "example": 1000000
                    },
                    "status": {
                        "type": "string",
                        "description": "Order Status",
                        "example": "processed",
                        "enum": [
                            "processed",
                            "paid"
                        ]
                    }
                }
            },
            "BuyResponse": {
                "type": "object",
                "properties": {
                    "product_name": {
                        "type": "string",
                        "description": "name of product",
                        "example": "Laptop"
                    },
                    "product_price": {
                        "type": "integer",
                        "format": "int64",
                        "example": 10000
                    },
                    "product_discount": {
                        "type": "integer",
                        "format": "float64",
                        "example": 0.1
                    },
                    "product_description": {
                        "type": "string",
                        "description": "description of product"
                    },
                    "total_harga": {
                        "type": "integer",
                        "format": "int64",
                        "example": 1000000
                    },
                    "pay_url": {
                        "type": "string",
                        "description": "link payment product"
                    }
                }
            },
            "ApiResponseOrder": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "message": {
                        "type": "string"
                    },
                    "data": {
                        "$ref": "#/components/schemas/OrderResponse"
                    }
                }
            },
            "ApiResponseBuy": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "message": {
                        "type": "string"
                    },
                    "data": {
                        "$ref": "#/components/schemas/BuyResponse"
                    }
                }
            },
            "ApiResponsePay": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "message": {
                        "type": "string"
                    },
                    "data": {
                        "$ref": "#/components/schemas/PaymentResponse"
                    }
                }
            },
            "ApiResponseHistoryOrder": {
                "type": "object",
                "properties": {
                    "_metadata": {
                        "$ref": "#/components/schemas/Metadata"
                    },
                    "data": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/OrderResponse"
                        }
                    }
                }
            },
            "Cart": {
                "required": [
                    "userId",
                    "productId",
                    "total"
                ],
                "type": "object",
                "properties": {
                    "userId": {
                        "type": "integer",
                        "format": "int64",
                        "example": 1
                    },
                    "productId": {
                        "type": "integer",
                        "format": "int64",
                        "example": 1
                    },
                    "total": {
                        "type": "integer",
                        "format": "int64",
                        "example": 10
                    }
                }
            },
            "CartResponse": {
                "type": "object",
                "properties": {
                    "product_name": {
                        "type": "string",
                        "description": "name of product",
                        "example": "Laptop"
                    },
                    "product_price": {
                        "type": "integer",
                        "format": "int64",
                        "example": 10000
                    },
                    "product_owner": {
                        "type": "string",
                        "description": "owner of product",
                        "example": "John Doe"
                    },
                    "product_expire": {
                        "type": "string",
                        "description": "time expire product"
                    },
                    "product_discount": {
                        "type": "integer",
                        "format": "float64",
                        "example": 0.1
                    },
                    "product_description": {
                        "type": "string",
                        "description": "description of product"
                    },
                    "total_beli": {
                        "type": "integer",
                        "format": "int64",
                        "example": 4
                    },
                    "pay_url": {
                        "type": "string",
                        "description": "link payment product"
                    }
                }
            },
            "ApiResponseCart": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "message": {
                        "type": "string"
                    },
                    "data": {
                        "$ref": "#/components/schemas/CartResponse"
                    }
                }
            },
            "ApiResponseListCart": {
                "type": "object",
                "properties": {
                    "_metadata": {
                        "$ref": "#/components/schemas/Metadata"
                    },
                    "data": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/CartResponse"
                        }
                    }
                }
            },
            "Metadata": {
                "type": "object",
                "properties": {
                    "page": {
                        "type": "integer",
                        "format": "int64",
                        "example": 1
                    },
                    "per_page": {
                        "type": "integer",
                        "format": "int64",
                        "example": 10
                    },
                    "total_data": {
                        "type": "integer",
                        "format": "int64",
                        "example": 100
                    },
                    "total_page": {
                        "type": "integer",
                        "format": "int64",
                        "example": 10
                    }
                }
            },
            "ApiResponse": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "message": {
                        "type": "string"
                    },
                    "data": {
                        "type": "string",
                        "example": "nil"
                    }
                }
            }
        },
        "securitySchemes": {
            "authorization": {
                "type": "apiKey",
                "name": "authorization",
                "in": "header"
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "http://localhost:3000",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Lyshitea API",
	Description:      "Documentation Lysithea API Project",
	InfoInstanceName: "Lysithea API",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
